name: spiketurnpike_postanalysis
channels:
  - defaults
dependencies:
  - python=3.9  # specify your python version
  - numpy
  - opencv
  - scikit-image
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - notebook
  - pillow
  - pip
  - xarrays
  - pip:
    mat73

      # - some-pip-package # if you need any pip packages that are not available in Conda
