name: mcs_mea_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - xarray
  - h5py
  - ipykernel
  - pip
  - pip:
      - McsPyDataTools
      - mat73
      - pyabf

